package org.example;

import java.util.List;
import java.util.Map;

public class Day2 {
    static String input =
            """
                    C Z
                    C Y
                    B X
                    A Z
                    C Z
                    B X
                    C Z
                    B Z
                    A Z
                    A Z
                    B Z
                    B X
                    C Z
                    C Z
                    A Z
                    B Y
                    B X
                    C Y
                    B X
                    B X
                    A Y
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Z
                    B X
                    A X
                    A Z
                    B Y
                    B X
                    A Z
                    B X
                    C Z
                    A Z
                    C Z
                    A Z
                    A Z
                    B X
                    C X
                    B X
                    A X
                    B X
                    A Z
                    A Z
                    B X
                    B Y
                    B Y
                    B Y
                    C Z
                    A Z
                    A Z
                    C X
                    B X
                    C Y
                    B X
                    C Z
                    A Z
                    C Z
                    B X
                    B X
                    B Z
                    B X
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    B X
                    C Z
                    C Y
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A X
                    A Z
                    A Z
                    C Z
                    C Y
                    A Z
                    C Y
                    A Z
                    A Z
                    C Y
                    C Z
                    C Z
                    A Z
                    B Y
                    B X
                    B Y
                    C Z
                    A Z
                    A Z
                    A Z
                    B Z
                    C Z
                    A Z
                    B X
                    C Y
                    A Z
                    B X
                    A Z
                    B Z
                    A Z
                    B X
                    A Z
                    B Y
                    A Z
                    A Z
                    C Y
                    A Z
                    B Z
                    A Z
                    A Y
                    B Y
                    C Z
                    A Z
                    B X
                    C Z
                    C Z
                    B X
                    C Z
                    C Z
                    A Z
                    B X
                    C Z
                    C Z
                    A Z
                    C Y
                    A Z
                    A Z
                    B Y
                    C Y
                    A Z
                    B X
                    B Y
                    B X
                    B X
                    A Z
                    C Y
                    A Z
                    C Y
                    A Z
                    B Y
                    C Z
                    A Z
                    A Z
                    C Y
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    C Z
                    A Z
                    C Z
                    B Z
                    C Z
                    A Z
                    C Y
                    B X
                    C Z
                    C Z
                    A Z
                    C Y
                    A Z
                    B Y
                    B X
                    A Z
                    C Y
                    C Z
                    B X
                    C X
                    B X
                    C Y
                    B X
                    B X
                    C Z
                    B X
                    A Z
                    C X
                    A Z
                    C Z
                    B X
                    C Y
                    A Z
                    A Z
                    C Z
                    C Y
                    A Z
                    A Z
                    A Z
                    B X
                    A Y
                    B X
                    C X
                    C Z
                    B X
                    C Z
                    C X
                    A Z
                    C Z
                    B Z
                    A X
                    A Z
                    C Y
                    A Z
                    C Z
                    C Z
                    B X
                    C Z
                    A X
                    C Y
                    C Z
                    C Z
                    C Z
                    B Y
                    C X
                    B X
                    A Z
                    B Y
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Y
                    A Y
                    C Y
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B Y
                    B X
                    B X
                    A Z
                    C X
                    C Y
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A X
                    A Z
                    C Z
                    A Z
                    B Y
                    A Y
                    A Y
                    C Y
                    C Y
                    B X
                    B Y
                    A Z
                    A Z
                    C X
                    A Z
                    B X
                    C Y
                    A Y
                    A Y
                    A Z
                    C Y
                    C Z
                    B X
                    A Z
                    C Y
                    B X
                    C Z
                    A Z
                    B X
                    A Z
                    C Y
                    B X
                    C Z
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    C Y
                    C Z
                    A Z
                    B X
                    C Z
                    C Y
                    A Z
                    A Z
                    C Y
                    A Z
                    C Z
                    B X
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Y
                    C Y
                    B X
                    B Z
                    B X
                    A Z
                    B Y
                    B Y
                    A Z
                    A Z
                    A Z
                    B Y
                    B Y
                    C Y
                    A Y
                    A Z
                    C X
                    B X
                    A Y
                    B Y
                    C Y
                    A Z
                    B Z
                    C Y
                    C Z
                    B X
                    A Z
                    A X
                    B X
                    C Y
                    B Z
                    A Z
                    B Y
                    A Z
                    B X
                    A Z
                    B X
                    A Z
                    C X
                    C Y
                    C Z
                    B X
                    C Z
                    C Y
                    A Z
                    C X
                    C Z
                    A Z
                    C Y
                    A Y
                    C Y
                    C Y
                    B Y
                    A Z
                    A Z
                    A Y
                    A Z
                    C Z
                    B X
                    A Y
                    B X
                    B Y
                    B X
                    A Z
                    C Z
                    C Z
                    C Y
                    B X
                    C Z
                    A X
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    A Z
                    A Z
                    B Z
                    B X
                    B X
                    C Y
                    C Z
                    C Z
                    A Y
                    B X
                    C Z
                    C X
                    C Z
                    B Y
                    A Z
                    B X
                    B Y
                    B X
                    A Z
                    B X
                    B X
                    A Z
                    A Z
                    C X
                    B X
                    C Z
                    C X
                    A Z
                    A X
                    C Z
                    A Z
                    A Z
                    C Z
                    B Z
                    C Z
                    B X
                    A Z
                    A Z
                    C Z
                    A Y
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    B Y
                    A Z
                    A Y
                    A X
                    B X
                    A Z
                    A Z
                    C Y
                    C Y
                    A Z
                    C X
                    A Z
                    A Y
                    A Z
                    B Y
                    A Z
                    A Y
                    B X
                    C Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    C Y
                    A Z
                    C Z
                    C Y
                    B Y
                    B X
                    A Z
                    B Y
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    C Z
                    A Z
                    C Z
                    B X
                    B X
                    B Y
                    A Y
                    C Y
                    B X
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    C Z
                    A X
                    B X
                    B Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B Y
                    A Y
                    C Z
                    B X
                    B X
                    C Y
                    A Y
                    A Z
                    C X
                    B Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Y
                    B Y
                    C Z
                    B X
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Y
                    B X
                    C Y
                    A Z
                    A Z
                    A Z
                    C X
                    B X
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Y
                    C Y
                    A Z
                    A Z
                    B X
                    A Z
                    B Y
                    A Y
                    B X
                    A X
                    A Z
                    C Z
                    C Z
                    C Y
                    A Z
                    B Y
                    A Z
                    C X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B Y
                    A Y
                    A Z
                    A Z
                    B X
                    C Y
                    B X
                    B Y
                    C Y
                    C X
                    A Z
                    A Z
                    B Y
                    A Z
                    B Y
                    C Y
                    C Y
                    A Z
                    C Y
                    A Z
                    C Z
                    A Z
                    B X
                    A Z
                    A Z
                    A X
                    A Z
                    A Z
                    A Z
                    A Z
                    B Z
                    C X
                    B Y
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    B X
                    C Y
                    C Z
                    A Z
                    A Z
                    C Z
                    B X
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A X
                    C Z
                    C Y
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    B Z
                    A Z
                    C Y
                    A Z
                    A Z
                    B Y
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    C Y
                    A Y
                    C Y
                    B Z
                    B X
                    B Y
                    A Z
                    A Z
                    C Y
                    A Z
                    A Y
                    B Z
                    A Z
                    C Y
                    A Z
                    A Z
                    A X
                    A Z
                    B Y
                    B Y
                    A Z
                    A Z
                    A Z
                    C Z
                    C Z
                    A Y
                    C Y
                    B X
                    A Y
                    B X
                    B Y
                    C X
                    C Y
                    C Y
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Y
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A X
                    C Y
                    B X
                    A Z
                    A Y
                    C Y
                    C Y
                    A X
                    A Z
                    C X
                    C Z
                    A Z
                    C X
                    A Z
                    A Z
                    B Y
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    B X
                    A Z
                    A Z
                    C Z
                    C Z
                    A Z
                    C Z
                    B X
                    A Z
                    A Z
                    B X
                    C Z
                    C Z
                    C Y
                    C Z
                    A Z
                    B X
                    A X
                    C Z
                    A X
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    C Y
                    A Z
                    A Z
                    A Z
                    C Z
                    A Y
                    A Y
                    B Y
                    A Z
                    A Z
                    C Y
                    C Z
                    B X
                    B X
                    A X
                    C Z
                    B X
                    A Z
                    A Z
                    A Z
                    B Z
                    A Z
                    C Y
                    B X
                    A Z
                    A Z
                    A Y
                    B Y
                    C Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B Y
                    A Z
                    C Y
                    B X
                    B Z
                    C X
                    B X
                    C Y
                    A X
                    C Z
                    A Z
                    B X
                    C X
                    A Y
                    C X
                    A Z
                    B X
                    B X
                    A Z
                    A Z
                    C Z
                    B X
                    B Z
                    C Y
                    C Z
                    A Z
                    B Y
                    A Z
                    A Z
                    B X
                    C Y
                    A Z
                    C Z
                    A Z
                    B Z
                    C Z
                    C Z
                    A Z
                    C Y
                    A Z
                    A Z
                    A Z
                    C Z
                    C X
                    B Y
                    C Y
                    A Z
                    C Y
                    C Y
                    C X
                    C Y
                    A Z
                    C Y
                    C Y
                    C X
                    C X
                    A Z
                    B X
                    A Z
                    C Y
                    A Z
                    B X
                    B X
                    B X
                    B X
                    B X
                    B Y
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    C Z
                    C Z
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    A Y
                    A X
                    C Z
                    A Z
                    A Z
                    C Z
                    B X
                    C Z
                    B Y
                    C Z
                    A Y
                    A Z
                    C Y
                    B X
                    A Z
                    C Y
                    A Z
                    C Z
                    C Y
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C X
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    B X
                    A Z
                    A X
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    A Y
                    B X
                    B Z
                    A Z
                    B X
                    A Z
                    A Z
                    B Y
                    A Z
                    A Z
                    C Y
                    B Y
                    C X
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Y
                    B X
                    A Z
                    A Z
                    C X
                    A Z
                    C Z
                    A Z
                    B Y
                    A Z
                    A Y
                    C Z
                    C Z
                    A Y
                    A Y
                    A Z
                    A X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    C Z
                    A Z
                    A Y
                    B X
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    B X
                    B Z
                    A Z
                    A X
                    B Y
                    A Z
                    B X
                    A Z
                    C Z
                    B X
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    B Z
                    A Z
                    C Z
                    A Z
                    C Z
                    B X
                    A Z
                    B Z
                    A Z
                    C Z
                    C Z
                    B Y
                    C Z
                    A Z
                    A Z
                    C Y
                    A Z
                    A Z
                    B X
                    B Y
                    C Z
                    A Z
                    C Z
                    A Z
                    C Z
                    A Z
                    B X
                    A X
                    B Y
                    A Z
                    C Z
                    A Z
                    C Z
                    C Y
                    B X
                    C Z
                    C Z
                    B Y
                    B X
                    C Z
                    B X
                    C Y
                    A Z
                    C Y
                    C Y
                    A Z
                    B X
                    A Z
                    C X
                    C Z
                    B Y
                    C Z
                    B Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    B Y
                    C Y
                    C X
                    C Y
                    B Y
                    B X
                    A Z
                    C Z
                    B X
                    B Y
                    A Z
                    B Y
                    A Z
                    A Y
                    B X
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C X
                    B Y
                    C Z
                    C Z
                    A X
                    C Z
                    A Z
                    C Z
                    B Y
                    A Z
                    B Y
                    A Z
                    A Z
                    A Z
                    B Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Y
                    A Z
                    C Z
                    A Z
                    C X
                    A Z
                    A Z
                    A Z
                    C Z
                    A Y
                    A Z
                    A Z
                    B Z
                    A Z
                    A Z
                    A Z
                    C Z
                    C Z
                    A Y
                    A Z
                    A X
                    C Y
                    C Y
                    B Z
                    A Y
                    C Z
                    A Z
                    C Z
                    C Z
                    A Z
                    A X
                    A Z
                    B Y
                    C Z
                    B Y
                    A Z
                    B X
                    A Z
                    A Y
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Z
                    C Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C X
                    C Z
                    C X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    B Y
                    B X
                    A Z
                    C Z
                    B Z
                    A Z
                    C Y
                    A Z
                    C Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Y
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    C Y
                    A Z
                    C X
                    A Z
                    C X
                    C Z
                    C Z
                    A Z
                    A Z
                    B Y
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    C Z
                    B Z
                    A Z
                    A Y
                    B Y
                    A Z
                    C Z
                    B X
                    C X
                    C Y
                    C Y
                    C Z
                    C X
                    B X
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    A Y
                    A Z
                    B X
                    A Y
                    A Z
                    A Y
                    C Y
                    A Y
                    A Z
                    A Z
                    B X
                    C X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Y
                    B X
                    A Z
                    A Z
                    B Y
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    C Y
                    C Y
                    B Y
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    A Y
                    C Z
                    C Y
                    C Z
                    C X
                    C Z
                    C Y
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    C Z
                    A Z
                    C Z
                    C X
                    B Y
                    C X
                    B X
                    C Z
                    B X
                    C Z
                    A Z
                    A Y
                    B Y
                    A Z
                    A Z
                    C X
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    C Y
                    C Z
                    B X
                    B X
                    A Z
                    C X
                    A Z
                    B X
                    C Y
                    A Z
                    A Y
                    B X
                    C Y
                    B X
                    A X
                    A Z
                    A Z
                    A Z
                    C Z
                    B Y
                    C Z
                    B Y
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    C Y
                    B X
                    A Z
                    C X
                    A Z
                    C Z
                    B Z
                    A Z
                    A Z
                    A Z
                    B Z
                    A Y
                    A Z
                    A Z
                    C Z
                    B Z
                    A X
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A X
                    C Z
                    A Z
                    C Z
                    B X
                    B X
                    C Y
                    B X
                    A Z
                    A Z
                    C Y
                    C Z
                    B X
                    C Y
                    A Y
                    B X
                    B X
                    C X
                    A Z
                    A Z
                    C Z
                    A Z
                    C Z
                    C Z
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    B Y
                    B Y
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    B X
                    A Z
                    C Z
                    C Z
                    B X
                    C Y
                    A Z
                    A X
                    B X
                    B X
                    B Y
                    B Y
                    A Z
                    C Z
                    A Z
                    C Z
                    A Z
                    C Y
                    B X
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    C Y
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    A Y
                    C Y
                    C Z
                    A Z
                    A Z
                    B X
                    C Y
                    A Z
                    C X
                    A Z
                    B X
                    A Z
                    A Z
                    B Y
                    B X
                    C Z
                    A Z
                    B X
                    A Y
                    A Z
                    B Z
                    A Z
                    C Y
                    B Y
                    C Z
                    C X
                    B X
                    A X
                    B X
                    B Z
                    B X
                    B Y
                    B X
                    C Y
                    B X
                    A Y
                    B Z
                    B X
                    C X
                    B X
                    A Z
                    A Z
                    B X
                    B X
                    A Z
                    A Z
                    C Y
                    B Y
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    C Y
                    C X
                    A Z
                    A Z
                    A Z
                    A Z
                    B Y
                    A Z
                    A Z
                    C Z
                    C Z
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    C Y
                    B X
                    C Z
                    A Z
                    C Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C X
                    C Z
                    B X
                    B X
                    B X
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    C X
                    A Z
                    C Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A X
                    B X
                    A Z
                    A Z
                    A X
                    A Z
                    B Y
                    A Z
                    A Z
                    A Z
                    C Y
                    C Y
                    A Z
                    C Y
                    C X
                    A Z
                    B Y
                    A Z
                    A Z
                    B Y
                    A Z
                    A Z
                    A Z
                    C Y
                    B X
                    A Z
                    A Z
                    A Z
                    A X
                    A Z
                    A Y
                    A Y
                    A Z
                    C Z
                    B Y
                    C Y
                    B X
                    B X
                    B X
                    A Z
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    A Z
                    C Z
                    A Z
                    C Y
                    A Z
                    B X
                    C Z
                    C Y
                    A Z
                    C X
                    A Y
                    B Z
                    C Z
                    C Y
                    A Z
                    A Z
                    A Z
                    A Y
                    A Y
                    C Y
                    B X
                    C Z
                    B X
                    C Y
                    B X
                    B X
                    A Z
                    A Z
                    C Z
                    A Z
                    B X
                    A Z
                    B X
                    C Y
                    C Z
                    A X
                    B X
                    B X
                    C Z
                    C Z
                    C Z
                    C Z
                    C Z
                    A X
                    A Z
                    B X
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    B X
                    B Y
                    C Z
                    C Y
                    A Z
                    C Z
                    B X
                    C Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B X
                    B Z
                    A X
                    B Y
                    C Z
                    A Z
                    A X
                    A Y
                    A Z
                    C Y
                    A Z
                    C Z
                    A Z
                    A Z
                    A X
                    A Z
                    A Y
                    B Z
                    A Z
                    A Z
                    B X
                    B Y
                    A Z
                    C Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    C Y
                    B X
                    B X
                    A Z
                    C Y
                    B Z
                    A Z
                    B X
                    B X
                    B X
                    B Y
                    C Z
                    B Z
                    A X
                    B X
                    A Y
                    A Z
                    B X
                    B X
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    C Z
                    C Y
                    B X
                    B X
                    C X
                    A Z
                    A X
                    A Z
                    C Y
                    C Z
                    C Y
                    C Z
                    C Y
                    C Y
                    B X
                    B Y
                    A Z
                    C X
                    C Z
                    B X
                    C Z
                    C Z
                    B X
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    C Y
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Y
                    A Z
                    C Z
                    C Z
                    C Z
                    A Z
                    B X
                    B Y
                    A Z
                    C X
                    A Y
                    A Y
                    C Y
                    C Y
                    A Z
                    C Y
                    B X
                    C X
                    B X
                    C Y
                    A Z
                    A Y
                    B X
                    B X
                    A Z
                    A Z
                    A Z
                    A X
                    A Z
                    B X
                    B Y
                    A Y
                    C Z
                    B Y
                    A X
                    A Z
                    A X
                    A Z
                    A X
                    A Y
                    C Y
                    C Z
                    A Z
                    A Z
                    A Z
                    C Y
                    A Z
                    A X
                    A Z
                    A X
                    A Z
                    A Z
                    B X
                    C X
                    C Y
                    C Z
                    B X
                    A X
                    C Z
                    C Z
                    C X
                    A Z
                    C Z
                    C Y
                    A Z
                    C Z
                    C Z
                    B X
                    A Z
                    B Y
                    B X
                    B X
                    C Z
                    A Z
                    A Z
                    B X
                    B X
                    A Z
                    C Z
                    B X
                    A Y
                    B Z
                    C X
                    A Z
                    C Y
                    A Z
                    A Z
                    B X
                    C Z
                    C Y
                    A Z
                    B X
                    B Y
                    A Z
                    B X
                    B Z
                    C X
                    A Z
                    C Y
                    C Z
                    B X
                    C X
                    C Y
                    A X
                    C X
                    C Y
                    B Y
                    A Z
                    C Y
                    C Z
                    A Z
                    A Z
                    A Y
                    A Z
                    C Y
                    C X
                    B X
                    C Y
                    A Z
                    B Y
                    A Z
                    B X
                    A Z
                    C X
                    A Z
                    C Z
                    B Y
                    B Y
                    B Y
                    C Y
                    A Z
                    A Y
                    C Z
                    C Y
                    B Y
                    A Z
                    B Y
                    B X
                    A Z
                    B Z
                    A Z
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    C Z
                    B X
                    B X
                    C Z
                    A Z
                    C Z
                    B Y
                    C Y
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Y
                    A Z
                    B Y
                    A Z
                    C X
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    B Y
                    A Y
                    C X
                    A Y
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    C Z
                    A Z
                    B X
                    C Y
                    C Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A X
                    B X
                    B X
                    A Z
                    B X
                    C Y
                    A Y
                    A Z
                    A Z
                    C X
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    A Y
                    B X
                    A Z
                    B X
                    B X
                    B X
                    B X
                    A Y
                    B X
                    A Z
                    A Z
                    B X
                    C Y
                    B X
                    C Z
                    B X
                    A Z
                    C X
                    A Z
                    B Y
                    C Z
                    B X
                    A Z
                    A Z
                    C Y
                    C Y
                    A Z
                    A Z
                    C Z
                    A Y
                    A Z
                    C X
                    C Z
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    A Y
                    B Z
                    B X
                    A Z
                    A X
                    B X
                    A Z
                    A Z
                    A Y
                    C Z
                    A Z
                    A Z
                    C Z
                    C Z
                    A X
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    A Y
                    C Y
                    B X
                    C Z
                    A Z
                    C Y
                    B Y
                    A Z
                    B Y
                    C Z
                    A Z
                    A X
                    B X
                    B X
                    A Z
                    A X
                    A Z
                    A Z
                    A Z
                    A Z
                    B Z
                    A Y
                    A Z
                    A X
                    C Y
                    A Z
                    B X
                    B Y
                    B X
                    C Z
                    A Z
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    B X
                    C Y
                    C Z
                    A Z
                    B Z
                    C Z
                    B X
                    C Y
                    A Z
                    C Z
                    B X
                    B X
                    A Y
                    A Z
                    B Z
                    B X
                    C Z
                    A Z
                    C Y
                    B Y
                    A Z
                    B Y
                    A Z
                    C Z
                    B X
                    B X
                    B X
                    C Z
                    A X
                    B Y
                    B Y
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    C Z
                    A Z
                    C Y
                    C Z
                    A Z
                    A X
                    A Z
                    A Z
                    A Z
                    B X
                    B Y
                    B X
                    A Z
                    A Z
                    C Z
                    A Z
                    C Z
                    A Z
                    A Z
                    B X
                    A Z
                    A Z
                    C Y
                    A Z
                    B X
                    A Z
                    A Z
                    B X
                    A Z
                    C Z
                    A Z
                    B X
                    A Z
                    A Z
                    A Z
                    C Z
                    B Y
                    A Z
                    B X
                    C X
                    A Z
                    B X
                    A Z
                    C Y
                    A Z
                    A Y
                    A Z
                    B Z
                    B X
                    C Z
                    A Z
                    C Z
                    C Y
                    B Y
                    B X
                    B Y
                    C Y
                    C Y
                    A Z
                    C Y
                    A X
                    A Z
                    B Y
                    A Z
                    B X
                    A Y
                    C Y
                    B X
                    C Y
                    B X
                    A Z
                    A X
                    B Y
                    B X
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    C Z
                    A Z
                    A Y
                    B X
                    B X
                    C Z
                    A Z
                    A Z
                    C X
                    B Z
                    C Z
                    B X
                    A Z
                    A Y
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    B Z
                    B X
                    A Z
                    B X
                    C Y
                    C Z
                    A Z
                    B X
                    B X
                    A Z
                    C X
                    A Z
                    B Y
                    A Z
                    C Y
                    B X
                    A Y
                    B Y
                    C Y
                    B X
                    B X
                    B Y
                    C Y
                    B X
                    A Z
                    C X
                    A Z
                    B X
                    A Z
                    A Y
                    A Z
                    A X
                    C X
                    C Y
                    A Z
                    A Z
                    C Y
                    A Z
                    A Z
                    A X
                    C Z
                    C Y
                    A Z
                    A Z
                    B X
                    B X
                    C Z
                    B X
                    A Z
                    C Y
                    B X
                    B X
                    C Z
                    A X
                    A Z
                    B Z
                    C Z
                    C Y
                    A Z
                    C Z
                    C Z
                    B Y
                    C Y
                    B Y
                    C Z
                    A Z
                    C Z
                    B X
                    A Z
                    B Y
                    B Y
                    C Y
                    C Y
                    A Z
                    C Z
                    C Z
                    A Z
                    A Z
                    C X
                    A Z
                    A Z
                    C X
                    A Z
                    A Z
                    A Y
                    A X
                    C X
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A X
                    A X
                    B Y
                    A X
                    A Z
                    A X
                    B X
                    B X
                    A Z
                    C Y
                    A Z
                    C Y
                    C Y
                    B X
                    B X
                    A Z
                    B Z
                    B X
                    C X
                    B X
                    A Z
                    A Z
                    A Z
                    B X
                    C Y
                    C Z
                    A Z
                    B Y
                    C Y
                    C X
                    A Z
                    A Z
                    A Z
                    A Z
                    A X
                    C Z
                    A Z
                    B X
                    A Z
                    A Z
                    C Z
                    C X
                    C Z
                    A Z
                    C Y
                    B Y
                    A Z
                    C Z
                    B X
                    B Z
                    A Z
                    A Z
                    A Y
                    C Y
                    C Z
                    C Z
                    A Z
                    A Z
                    C Z
                    B X
                    A Z
                    A Z
                    A Z
                    B X
                    A Z
                    B X
                    B X
                    A Z
                    C Y
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    C Y
                    B X
                    A Z
                    C Z
                    A Z
                    C Z
                    A X
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    B X
                    C Y
                    B Z
                    A Z
                    C X
                    A Z
                    C Z
                    C Z
                    C Y
                    C Y
                    B X
                    A Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Y
                    A Z
                    A Z
                    A Z
                    C Y
                    B Y
                    C Z
                    C Z
                    A Z
                    A Z
                    A Z
                    A Y
                    C Z
                    A Z
                    A Y
                    A Z
                    A Z
                    A Z
                    B X
                    B X
                    C Y
                    B X
                    A Z
                    A Z
                    A X
                    C Z
                    C Y
                    A Z
                    C Y
                    A Z
                    A Z
                    A Z
                    C X
                    B X
                    A Z
                    C X
                    C Y
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    A Z
                    C Z
                    B X
                    C X
                    C Z
                    B Y
                    B Z
                    B Z
                    C Y
                    A Z
                    B X
                    B X
                    A Z
                    A Z
                    A Z
                    B Z
                    B Z
                    A Z
                    C Z
                    A Y
                    C X
                    C Y
                    A X
                    C Y
                    A Z
                    C X
                    A Z
                    B X
                    C Z
                    B X
                    B Z
                    A Z
                    A X
                    A Z
                    B X
                    C Y
                    B Y
                    A Z
                    C Z
                    A Y
                    A Z
                    C Y
                    A Z
                    C Y
                    B X
                    A Z
                    A Z
                    A Z
                    A Z
                    B Y
                    A X
                    A Z
                    C Z
                    A Z
                    C Z
                    B X
                    C Z
                    A Z
                    B Y
                    A Z
                    C Y
                    C Y
                    C Z
                    A Z
                    A Z
                    A Y
                    B X
                    A Z
                    A Z
                    C X
                    B X
                    C X
                    A Y
                    A Z
                    A X
                    B X
                    A Z
                    B Y
                    C Z
                    C Z
                    C Y
                    A Z
                    A Y
                    A Z
                    A Z
                    B Z
                    C Y
                    A Z
                    A Z
                    B Y
                    """;

    static String testInput = """
            A Y
            B X
            C Z
            """;
    //X: rock, Y: paper, Z: scissors
    static Map<String, Integer> pointMap = Map.of("X", 1, "Y", 2, "Z", 3);
    static Map<String, Integer> winMap = Map.of("A X", 3, "A Y", 6, "A Z", 0,
            "B X", 0, "B Y", 3, "B Z", 6,
            "C X", 6, "C Y", 0, "C Z", 3);

    //x: lose Y: draw Z: win
    static Map<String, Integer> roundResultMap = Map.of("X", 0, "Y", 3, "Z", 6);
    //A: rock, B: paper, C: scissors
    static Map<String, Integer> round2WinMap = Map.of("A X", 3, "A Y", 1, "A Z", 2,
            "B X", 1, "B Y", 2, "B Z", 3,
            "C X", 2, "C Y", 3, "C Z", 1);

    public static void main(String[] args) {
        List<String> inputArray = List.of(input.split("\n"));
        int totalPoints = 0;
        for (String round : inputArray) {
            int roundScore = pointMap.get(round.substring(round.length() - 1));
            roundScore += winMap.get(round);
            totalPoints += roundScore;
        }
        System.out.println("round 1 result: " + totalPoints);
        totalPoints = 0;
        for (String round : inputArray) {
            int roundScore = roundResultMap.get(round.substring(round.length() - 1));
            roundScore += round2WinMap.get(round);
            totalPoints += roundScore;
        }
        System.out.println("round 2 result " + totalPoints);
    }
}
